import * as THREE from "three";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";
import { TransformControls } from "three/addons/controls/TransformControls.js";

const SIZE_LANDSCAPE = { w: 300, h: 169 }; // 16:9
const SIZE_PORTRAIT  = { w: 169, h: 300 }; // 9:16
const sizeFor = o => (o === "portrait" ? SIZE_PORTRAIT : SIZE_LANDSCAPE);

// ---------- Layers ----------
// Layer 0 = world (everyone sees). Layer 1 = main-only gizmos (frustums).
const LAYER_WORLD = 0;
const LAYER_GIZMO = 1;

// ---------- Shared scene ----------
const scene = new THREE.Scene();
const sphereGeoOuter = new THREE.SphereGeometry(500, 64, 32);
const sphereGeoMid   = new THREE.SphereGeometry(340, 64, 32);
const sphereGeoInner = new THREE.SphereGeometry(200, 64, 32);
const loader = new THREE.TextureLoader();

function loadEquirectTexture(url) {
  const tex = loader.load(url);
  tex.colorSpace = THREE.SRGBColorSpace;
  tex.minFilter = THREE.LinearFilter;
  tex.magFilter = THREE.LinearFilter;
  tex.generateMipmaps = false;
  return tex;
}

// World state lives in a single object so Save/Load can read it cleanly.
const state = {
  depth: false,
  overview: false,
  spheres: [], // active sphere meshes, regenerated by useSingle/useDepthLayers
};

function disposeSpheres() {
  for (const m of state.spheres) {
    scene.remove(m);
    m.material.map?.dispose();
    m.material.dispose();
  }
  state.spheres = [];
}

function spheresSide() {
  return state.overview ? THREE.DoubleSide : THREE.BackSide;
}

function applySpheresSide() {
  for (const m of state.spheres) m.material.side = spheresSide();
}

function useSingle() {
  disposeSpheres();
  const tex = loadEquirectTexture("test.jpg");
  const mat = new THREE.MeshBasicMaterial({ map: tex, side: spheresSide() });
  const mesh = new THREE.Mesh(sphereGeoOuter, mat);
  scene.add(mesh);
  state.spheres.push(mesh);
}

function useDepthLayers() {
  disposeSpheres();
  const layers = [
    { src: "depth_far.png",  geo: sphereGeoOuter, order: 0 },
    { src: "depth_mid.png",  geo: sphereGeoMid,   order: 1 },
    { src: "depth_near.png", geo: sphereGeoInner, order: 2 },
  ];
  for (const l of layers) {
    const tex = loadEquirectTexture(l.src);
    const mat = new THREE.MeshBasicMaterial({
      map: tex,
      side: spheresSide(),
      transparent: true,
      depthWrite: false,
    });
    const mesh = new THREE.Mesh(l.geo, mat);
    mesh.renderOrder = l.order;
    scene.add(mesh);
    state.spheres.push(mesh);
  }
}

useSingle();

// ---------- Main renderer + camera ----------
const stage = document.getElementById("stage");
const mainCanvas = document.getElementById("main-canvas");
const mainRenderer = new THREE.WebGLRenderer({ canvas: mainCanvas, antialias: true });
mainRenderer.setPixelRatio(window.devicePixelRatio);
mainRenderer.autoClear = false; // we drive clears explicitly so we can overlay an axes widget

const mainCam = new THREE.PerspectiveCamera(75, 1, 0.1, 6000);
mainCam.rotation.order = "YXZ";
mainCam.position.set(0, 0, 0);
mainCam.layers.enableAll(); // main view sees world + all gizmos

function fitMain() {
  const w = stage.clientWidth, h = stage.clientHeight;
  mainRenderer.setSize(w, h, false);
  mainCam.aspect = w / h;
  mainCam.updateProjectionMatrix();
}
fitMain();
window.addEventListener("resize", fitMain);

// ---------- OrbitControls (active in overview mode) ----------
const orbit = new OrbitControls(mainCam, mainCanvas);
orbit.enabled = false;
orbit.target.set(0, 0, 0);
orbit.minDistance = 100;
orbit.maxDistance = 4500;
orbit.enableDamping = true;
orbit.dampingFactor = 0.08;
orbit.rotateSpeed = 0.5;
orbit.zoomSpeed = 0.9;

// ---------- TransformControls (camera handles) ----------
const transform = new TransformControls(mainCam, mainCanvas);
transform.size = 0.65;
transform.setSpace("world");
// In Three.js r169+, TransformControls itself is no longer an Object3D — it
// exposes its draggable gizmo via getHelper(). Older versions add directly.
const transformHelper = typeof transform.getHelper === "function" ? transform.getHelper() : transform;
scene.add(transformHelper);
let selectedMonitor = null;
let transformDragging = false;

function pinTransformToGizmoLayer() {
  // TransformControls spawns internal helper meshes; keep them off monitor cams.
  transformHelper.traverse(c => c.layers.set(LAYER_GIZMO));
}
pinTransformToGizmoLayer();
transform.addEventListener("dragging-changed", e => {
  transformDragging = e.value;
  if (state.overview) orbit.enabled = !e.value;
});
transform.addEventListener("change", () => {
  pinTransformToGizmoLayer();
  if (!selectedMonitor) return;
  // Translate handles update cam.position; rotate handles update cam.quaternion.
  selectedMonitor.offset.copy(selectedMonitor.cam.position);
  if (transform.getMode() === "rotate") {
    const eul = new THREE.Euler().setFromQuaternion(selectedMonitor.cam.quaternion, "YXZ");
    selectedMonitor.yaw = eul.y;
    selectedMonitor.pitch = THREE.MathUtils.clamp(eul.x, -Math.PI/2 + 0.01, Math.PI/2 - 0.01);
  }
  selectedMonitor.setSliders();
});

function selectMonitor(m) {
  selectedMonitor = m;
  if (m) {
    transform.attach(m.cam);
    pinTransformToGizmoLayer();
  } else {
    transform.detach();
  }
  for (const mon of monitors) mon.li.classList.toggle("selected", mon === m);
}

// ---------- Mouse-look + WASD + wheel zoom ----------
let yaw = 0, pitch = 0;
let dragging = false, lastX = 0, lastY = 0;
const keys = new Set();

// Track click-vs-drag so we can use mousedown/mouseup as a click selector
// without stealing drag events from OrbitControls or first-person look.
let pointerDownAt = null;

// CAPTURE-phase guard: if the user is starting a drag on a TransformControls
// handle (i.e. transform.axis is set on hover), suspend OrbitControls so it
// doesn't simultaneously orbit while the handle is being dragged. The bubble-
// phase pointerdown below also short-circuits mouselook in the same case.
mainCanvas.addEventListener("pointerdown", () => {
  if (transform.axis !== null) {
    if (state.overview && orbit.enabled) {
      orbit.enabled = false;
      const release = () => {
        window.removeEventListener("pointerup", release, true);
        if (!transformDragging) orbit.enabled = true;
      };
      window.addEventListener("pointerup", release, true);
    }
  }
}, true);

mainCanvas.addEventListener("pointerdown", e => {
  pointerDownAt = { x: e.clientX, y: e.clientY, button: e.button };
  if (transform.axis !== null) return; // transform handle owns this click
  if (state.overview) return;          // orbit handles drag
  if (e.button !== 0) return;          // only left button
  dragging = true; lastX = e.clientX; lastY = e.clientY;
});
window.addEventListener("mouseup", () => { dragging = false; });
window.addEventListener("mousemove", e => {
  if (!dragging || state.overview) return;
  yaw   -= (e.clientX - lastX) * 0.0035;
  pitch -= (e.clientY - lastY) * 0.0035;
  pitch = Math.max(-Math.PI/2 + 0.01, Math.min(Math.PI/2 - 0.01, pitch));
  lastX = e.clientX; lastY = e.clientY;
});

const _raycaster = new THREE.Raycaster();
_raycaster.layers.set(LAYER_GIZMO);
const _ndc = new THREE.Vector2();
mainCanvas.addEventListener("pointerup", e => {
  if (!pointerDownAt) return;
  const moved = Math.hypot(e.clientX - pointerDownAt.x, e.clientY - pointerDownAt.y);
  const wasLeft = pointerDownAt.button === 0;
  pointerDownAt = null;
  if (!wasLeft || moved > 4) return; // it was a drag, not a click
  const rect = mainCanvas.getBoundingClientRect();
  _ndc.x = ((e.clientX - rect.left) / rect.width) * 2 - 1;
  _ndc.y = -((e.clientY - rect.top) / rect.height) * 2 + 1;
  _raycaster.setFromCamera(_ndc, mainCam);
  const hits = _raycaster.intersectObjects(monitors.map(m => m.body), false);
  selectMonitor(hits.length ? hits[0].object.userData.monitor : null);
});

mainCanvas.addEventListener("wheel", e => {
  if (state.overview) return; // orbit handles wheel zoom
  e.preventDefault();
  const next = mainCam.fov + Math.sign(e.deltaY) * 3;
  mainCam.fov = Math.max(10, Math.min(130, next));
  mainCam.updateProjectionMatrix();
}, { passive: false });

window.addEventListener("keydown", e => {
  if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement) return;
  const k = e.key.toLowerCase();
  if ("wasdqe".includes(k)) keys.add(k);
  if (k === "escape") selectMonitor(null);
  else if (k === "t" && selectedMonitor) transform.setMode("translate");
  else if (k === "r") {
    if (selectedMonitor) transform.setMode("rotate");
    else recenterMainCam();
  }
});
window.addEventListener("keyup", e => keys.delete(e.key.toLowerCase()));

function recenterMainCam() {
  yaw = 0; pitch = 0;
  if (state.overview) {
    mainCam.position.set(0, 200, 1100);
    orbit.target.set(0, 0, 0);
    orbit.update();
  } else {
    mainCam.position.set(0, 0, 0);
  }
}

const hudYaw   = document.getElementById("hud-yaw");
const hudPitch = document.getElementById("hud-pitch");
const hudFov   = document.getElementById("hud-fov");
const hudPos   = document.getElementById("hud-pos");

const _eulHud = new THREE.Euler();
function updateMainCam(dt) {
  if (state.overview) {
    // Orbit controls own camera rotation + zoom; we only call update for damping.
    orbit.update();
  } else {
    const dir = new THREE.Vector3();
    if (keys.has("w")) dir.z -= 1;
    if (keys.has("s")) dir.z += 1;
    if (keys.has("a")) dir.x -= 1;
    if (keys.has("d")) dir.x += 1;
    if (keys.has("q")) dir.y -= 1;
    if (keys.has("e")) dir.y += 1;
    if (dir.lengthSq() > 0) {
      dir.normalize().multiplyScalar(60 * dt);
      const cosY = Math.cos(yaw), sinY = Math.sin(yaw);
      const wx = dir.x * cosY + dir.z * sinY;
      const wz = -dir.x * sinY + dir.z * cosY;
      mainCam.position.x += wx;
      mainCam.position.y += dir.y;
      mainCam.position.z += wz;
      const cage = 150;
      const r = mainCam.position.length();
      if (r > cage) mainCam.position.multiplyScalar(cage / r);
    }
    mainCam.rotation.y = yaw;
    mainCam.rotation.x = pitch;
  }

  _eulHud.setFromQuaternion(mainCam.quaternion, "YXZ");
  hudYaw.textContent   = _eulHud.y.toFixed(2);
  hudPitch.textContent = _eulHud.x.toFixed(2);
  hudFov.textContent   = (mainCam.fov | 0).toString();
  hudPos.textContent   = `${mainCam.position.x.toFixed(0)},${mainCam.position.y.toFixed(0)},${mainCam.position.z.toFixed(0)}`;
}

// ---------- Frustum projection gizmo ----------
// Each camera draws four rays from its apex out to where the frustum corners
// pierce the panorama sphere, plus the four edges of the rectangle traced
// across the sphere's surface. Geometry lives in world space and is rebuilt
// every frame so it tracks position/rotation/fov/offset changes for free.
const PROJECTION_RADIUS = 500; // outermost panorama sphere
const EDGE_SEGMENTS = 24;      // samples per side of the projected rectangle

function makeProjectionGizmo(color) {
  const totalSegments = 4 + 4 * EDGE_SEGMENTS;
  const positions = new Float32Array(totalSegments * 2 * 3);
  const geo = new THREE.BufferGeometry();
  geo.setAttribute("position", new THREE.BufferAttribute(positions, 3));
  geo.setDrawRange(0, totalSegments * 2);
  const mat = new THREE.LineBasicMaterial({
    color, transparent: true, opacity: 0.9, depthTest: false, depthWrite: false,
  });
  const lines = new THREE.LineSegments(geo, mat);
  lines.layers.set(LAYER_GIZMO);
  lines.renderOrder = 999; // draw on top of opaque + transparent spheres
  lines.frustumCulled = false; // we don't keep a meaningful bounding volume
  return lines;
}

const _v_forward = new THREE.Vector3();
const _v_up      = new THREE.Vector3();
const _v_right   = new THREE.Vector3();
const _v_dir     = new THREE.Vector3();
const _v_pt      = new THREE.Vector3();

function updateProjectionGizmo(gizmo, cam, fovDeg, aspect) {
  cam.updateMatrixWorld(true);
  const camPos = cam.position;
  const q = cam.quaternion;
  _v_forward.set(0, 0, -1).applyQuaternion(q);
  _v_up     .set(0, 1, 0 ).applyQuaternion(q);
  _v_right  .set(1, 0, 0 ).applyQuaternion(q);
  const halfH = Math.tan(fovDeg * Math.PI / 360);
  const halfW = halfH * aspect;
  const positions = gizmo.geometry.attributes.position.array;

  // Ray-sphere intersection from a point inside the sphere centered at origin.
  // |camPos + t*D|^2 = R^2 with |D|=1  =>  t = -(camPos·D) + sqrt(...)
  const R2 = PROJECTION_RADIUS * PROJECTION_RADIUS;
  function intersect(out, dx, dy, dz) {
    _v_dir.set(dx, dy, dz).normalize();
    const b = camPos.dot(_v_dir);
    const c = camPos.lengthSq() - R2;
    const disc = b * b - c;
    const t = -b + Math.sqrt(Math.max(disc, 0));
    out.copy(camPos).addScaledVector(_v_dir, t);
  }

  // Convert an (sx, sy) NDC corner sample to a world-space ray direction.
  function rayDir(sx, sy, out) {
    out.copy(_v_forward)
       .addScaledVector(_v_right, sx * halfW)
       .addScaledVector(_v_up,    sy * halfH);
    return out;
  }

  let p = 0;
  function pushSeg(ax, ay, az, bx, by, bz) {
    positions[p++] = ax; positions[p++] = ay; positions[p++] = az;
    positions[p++] = bx; positions[p++] = by; positions[p++] = bz;
  }

  const cornersNDC = [[-1, +1], [+1, +1], [+1, -1], [-1, -1]];
  const cornerPts = cornersNDC.map(([sx, sy]) => {
    const d = rayDir(sx, sy, new THREE.Vector3());
    const out = new THREE.Vector3();
    intersect(out, d.x, d.y, d.z);
    return out;
  });

  // 4 rays: camera apex -> corner on sphere
  for (const c of cornerPts) {
    pushSeg(camPos.x, camPos.y, camPos.z, c.x, c.y, c.z);
  }

  // 4 curved edges along the sphere surface, sampled by tracing rays.
  const edges = [
    [-1, +1, +1, +1], // top
    [+1, +1, +1, -1], // right
    [+1, -1, -1, -1], // bottom
    [-1, -1, -1, +1], // left
  ];
  const tmpDir = new THREE.Vector3();
  let prev = new THREE.Vector3();
  let cur  = new THREE.Vector3();
  for (const [s0x, s0y, s1x, s1y] of edges) {
    rayDir(s0x, s0y, tmpDir);
    intersect(prev, tmpDir.x, tmpDir.y, tmpDir.z);
    for (let k = 1; k <= EDGE_SEGMENTS; k++) {
      const tn = k / EDGE_SEGMENTS;
      rayDir(s0x + (s1x - s0x) * tn, s0y + (s1y - s0y) * tn, tmpDir);
      intersect(cur, tmpDir.x, tmpDir.y, tmpDir.z);
      pushSeg(prev.x, prev.y, prev.z, cur.x, cur.y, cur.z);
      // swap prev/cur
      const t = prev; prev = cur; cur = t;
    }
  }

  gizmo.geometry.attributes.position.needsUpdate = true;
}

// ---------- Monitors ----------
const monitorList = document.getElementById("monitor-list");
const monitors = [];

const PALETTE = [0x6cb6ff, 0xff7b72, 0x7ee787, 0xd2a8ff, 0xffa657, 0x79c0ff, 0xf778ba, 0x56d4dd];

// Shared body geometry — small clickable proxy for each camera.
const _bodyGeo = new THREE.IcosahedronGeometry(8, 1);

class Monitor {
  constructor(opts = {}) {
    this.id = Monitor.nextId++;
    this.color = PALETTE[(this.id - 1) % PALETTE.length];
    this.yaw    = opts.yaw    ?? ((this.id - 1) * (Math.PI / 3)) % (Math.PI * 2);
    this.pitch  = opts.pitch  ?? 0;
    this.fov    = opts.fov    ?? 60;
    this.orientation = opts.orientation === "portrait" ? "portrait" : "landscape";
    this.offset = new THREE.Vector3(opts.offX ?? 0, opts.offY ?? 0, opts.offZ ?? 0);
    const initSize = sizeFor(this.orientation);

    this.cam = new THREE.PerspectiveCamera(this.fov, initSize.w / initSize.h, 0.1, 6000);
    this.cam.rotation.order = "YXZ";
    this.cam.layers.set(LAYER_WORLD); // monitors only render world layer
    // TransformControls requires its target to be in the scene graph so its
    // matrixWorld stays current. Adding a camera object is harmless — cameras
    // aren't rendered as scene geometry.
    scene.add(this.cam);

    this.gizmo = makeProjectionGizmo(this.color);
    scene.add(this.gizmo);

    // Solid body marker so the user has a clickable target in the main view.
    this.bodyMat = new THREE.MeshBasicMaterial({ color: this.color });
    this.body = new THREE.Mesh(_bodyGeo, this.bodyMat);
    this.body.layers.set(LAYER_GIZMO);
    this.body.userData.monitor = this;
    scene.add(this.body);

    const colorHex = "#" + this.color.toString(16).padStart(6, "0");
    this.li = document.createElement("li");
    this.li.className = "monitor";
    this.li.dataset.orientation = this.orientation;
    this.li.innerHTML = `
      <header>
        <span class="title"><span class="swatch" style="background:${colorHex}"></span>Camera ${this.id}</span>
        <button class="orient" title="Toggle landscape / portrait">${this.orientation === "portrait" ? "9:16" : "16:9"}</button>
        <button class="remove" title="Remove">×</button>
      </header>
      <canvas width="${initSize.w}" height="${initSize.h}"></canvas>
      <div class="controls">
        <span>yaw</span>   <input class="r-yaw"   type="range" min="${-Math.PI.toFixed(4)}" max="${Math.PI.toFixed(4)}" step="0.01" value="${this.yaw}">    <span class="v v-yaw">${this.yaw.toFixed(2)}</span>
        <span>pitch</span> <input class="r-pitch" type="range" min="${(-Math.PI/2).toFixed(4)}" max="${(Math.PI/2).toFixed(4)}" step="0.01" value="${this.pitch}"> <span class="v v-pitch">${this.pitch.toFixed(2)}</span>
        <span>fov</span>   <input class="r-fov"   type="range" min="20" max="120" step="1" value="${this.fov}">                                  <span class="v v-fov">${this.fov}°</span>
        <div class="sep"></div>
        <span>off-x</span> <input class="r-offX"  type="range" min="-300" max="300" step="1" value="${this.offset.x}"> <span class="v v-offX">${this.offset.x}</span>
        <span>off-y</span> <input class="r-offY"  type="range" min="-300" max="300" step="1" value="${this.offset.y}"> <span class="v v-offY">${this.offset.y}</span>
        <span>off-z</span> <input class="r-offZ"  type="range" min="-300" max="300" step="1" value="${this.offset.z}"> <span class="v v-offZ">${this.offset.z}</span>
      </div>
    `;
    this.canvas = this.li.querySelector("canvas");
    this.renderer = new THREE.WebGLRenderer({ canvas: this.canvas, antialias: true });
    this.renderer.setPixelRatio(1);
    this.renderer.setSize(initSize.w, initSize.h, false);

    const wire = (sel, fn) => {
      const input = this.li.querySelector(sel);
      input.addEventListener("input", e => fn(parseFloat(e.target.value)));
    };
    wire(".r-yaw",   v => { this.yaw = v;   this.li.querySelector(".v-yaw").textContent = v.toFixed(2); });
    wire(".r-pitch", v => { this.pitch = v; this.li.querySelector(".v-pitch").textContent = v.toFixed(2); });
    wire(".r-fov",   v => { this.fov = v; this.cam.fov = v; this.cam.updateProjectionMatrix(); this.li.querySelector(".v-fov").textContent = `${v|0}°`; });
    wire(".r-offX",  v => { this.offset.x = v; this.li.querySelector(".v-offX").textContent = `${v|0}`; });
    wire(".r-offY",  v => { this.offset.y = v; this.li.querySelector(".v-offY").textContent = `${v|0}`; });
    wire(".r-offZ",  v => { this.offset.z = v; this.li.querySelector(".v-offZ").textContent = `${v|0}`; });

    this.li.querySelector(".remove").addEventListener("click", e => { e.stopPropagation(); removeMonitor(this); });
    this.li.querySelector(".orient").addEventListener("click", e => {
      e.stopPropagation();
      this.setOrientation(this.orientation === "portrait" ? "landscape" : "portrait");
    });
    // Click anywhere on the card (header / canvas) selects this camera.
    this.li.addEventListener("click", () => selectMonitor(this));
  }
  setOrientation(o) {
    if (o !== "landscape" && o !== "portrait") return;
    if (o === this.orientation) return;
    this.orientation = o;
    const { w, h } = sizeFor(o);
    this.canvas.width = w; this.canvas.height = h;
    this.renderer.setSize(w, h, false);
    this.cam.aspect = w / h;
    this.cam.updateProjectionMatrix();
    this.li.dataset.orientation = o;
    this.li.querySelector(".orient").textContent = o === "portrait" ? "9:16" : "16:9";
  }
  setSliders() {
    const set = (sel, v, fmt) => {
      const input = this.li.querySelector(sel);
      input.value = v;
      const lbl = this.li.querySelector(sel.replace("r-", "v-"));
      if (lbl) lbl.textContent = fmt(v);
    };
    set(".r-yaw",   this.yaw,    v => v.toFixed(2));
    set(".r-pitch", this.pitch,  v => v.toFixed(2));
    set(".r-fov",   this.fov,    v => `${v|0}°`);
    set(".r-offX",  this.offset.x, v => `${v|0}`);
    set(".r-offY",  this.offset.y, v => `${v|0}`);
    set(".r-offZ",  this.offset.z, v => `${v|0}`);
  }
  update() {
    // While the user is dragging this camera with TransformControls, don't
    // overwrite cam.position/rotation — let the handle drive cam state, and
    // the change listener has already mirrored cam → offset/yaw/pitch.
    if (selectedMonitor !== this || !transformDragging) {
      this.cam.position.copy(this.offset);
      this.cam.rotation.y = this.yaw;
      this.cam.rotation.x = this.pitch;
    }
    this.body.position.copy(this.cam.position);
    this.body.quaternion.copy(this.cam.quaternion);
    updateProjectionGizmo(this.gizmo, this.cam, this.fov, this.cam.aspect);
  }
  render() {
    this.renderer.render(scene, this.cam);
  }
  toJSON() {
    return {
      yaw: this.yaw, pitch: this.pitch, fov: this.fov,
      offX: this.offset.x, offY: this.offset.y, offZ: this.offset.z,
      orientation: this.orientation,
    };
  }
  dispose() {
    if (selectedMonitor === this) selectMonitor(null);
    this.renderer.dispose();
    scene.remove(this.cam);
    scene.remove(this.gizmo);
    this.gizmo.geometry.dispose();
    this.gizmo.material.dispose();
    scene.remove(this.body);
    this.bodyMat.dispose();
    this.li.remove();
  }
}
Monitor.nextId = 1;

function addMonitor(opts) {
  const m = new Monitor(opts);
  monitors.push(m);
  monitorList.appendChild(m.li);
  return m;
}
function removeMonitor(m) {
  const i = monitors.indexOf(m);
  if (i < 0) return;
  monitors.splice(i, 1);
  m.dispose();
}
function clearMonitors() {
  while (monitors.length) removeMonitor(monitors[0]);
  Monitor.nextId = 1;
}

// ---------- UI wiring ----------
document.getElementById("add-cam").addEventListener("click", () => addMonitor());
document.getElementById("depth-toggle").addEventListener("change", e => {
  state.depth = e.target.checked;
  if (state.depth) useDepthLayers();
  else useSingle();
});
document.getElementById("overview-toggle").addEventListener("change", e => {
  state.overview = e.target.checked;
  applySpheresSide();
  recenterMainCam();
  orbit.enabled = state.overview;
});

document.getElementById("save-preset").addEventListener("click", () => {
  const data = {
    version: 1,
    depth: state.depth,
    overview: state.overview,
    main: {
      yaw, pitch, fov: mainCam.fov,
      pos: [mainCam.position.x, mainCam.position.y, mainCam.position.z],
    },
    cameras: monitors.map(m => m.toJSON()),
  };
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = `sphere-world-preset-${Date.now()}.json`;
  a.click();
  URL.revokeObjectURL(a.href);
});

const loadInput = document.getElementById("load-input");
document.getElementById("load-preset").addEventListener("click", () => loadInput.click());
loadInput.addEventListener("change", async () => {
  const file = loadInput.files?.[0];
  if (!file) return;
  try {
    const data = JSON.parse(await file.text());
    applyPreset(data);
  } catch (err) {
    console.error("preset load failed", err);
    alert("Couldn't read that preset file.");
  } finally {
    loadInput.value = "";
  }
});

function applyPreset(data) {
  if (!data || data.version !== 1) {
    alert("Unsupported preset version.");
    return;
  }
  // Depth + overview flags
  state.depth = !!data.depth;
  state.overview = !!data.overview;
  document.getElementById("depth-toggle").checked = state.depth;
  document.getElementById("overview-toggle").checked = state.overview;
  if (state.depth) useDepthLayers(); else useSingle();
  applySpheresSide();
  // Main camera
  if (data.main) {
    yaw = data.main.yaw ?? 0;
    pitch = data.main.pitch ?? 0;
    mainCam.fov = data.main.fov ?? 75;
    mainCam.updateProjectionMatrix();
    if (Array.isArray(data.main.pos)) mainCam.position.fromArray(data.main.pos);
  }
  // Monitors
  clearMonitors();
  for (const c of (data.cameras ?? [])) addMonitor(c);
}

// ---------- Defaults ----------
addMonitor({ yaw: 0 });
addMonitor({ yaw: Math.PI });

// Expose for debugging / scripted tests.
window.__app = {
  state, mainCam, monitors, scene, orbit, transform, transformHelper,
  THREE,
  yaw: () => yaw, pitch: () => pitch,
  setMain: (p) => { if (p.fov != null) { mainCam.fov = p.fov; mainCam.updateProjectionMatrix(); } if (p.yaw != null) yaw = p.yaw; if (p.pitch != null) pitch = p.pitch; if (p.pos) mainCam.position.set(...p.pos); },
  selectMonitor,
};

// ---------- Axes orientation overlay ----------
// Small Tinkercad-style world-orientation gizmo in the corner of the main view.
const axesScene = new THREE.Scene();
const axesHelper = new THREE.AxesHelper(50);
axesHelper.material.depthTest = false;
axesHelper.material.linewidth = 2;
axesScene.add(axesHelper);
const axesCam = new THREE.PerspectiveCamera(45, 1, 0.1, 500);
const _axesDir = new THREE.Vector3();

function renderAxesOverlay() {
  // Position the axes camera so it views the helper from the same direction
  // the main camera looks at the world — the gizmo mirrors the main view.
  mainCam.getWorldDirection(_axesDir);
  axesCam.position.copy(_axesDir).multiplyScalar(-120);
  axesCam.up.copy(mainCam.up);
  axesCam.lookAt(0, 0, 0);

  const w = mainRenderer.domElement.clientWidth;
  const h = mainRenderer.domElement.clientHeight;
  const size = 96;
  const x = 12, y = 12; // bottom-left in WebGL coords
  mainRenderer.setScissorTest(true);
  mainRenderer.setViewport(x, y, size, size);
  mainRenderer.setScissor(x, y, size, size);
  mainRenderer.clear(false, true, false); // clear depth only, in the scissor box
  mainRenderer.render(axesScene, axesCam);
  mainRenderer.setScissorTest(false);
  mainRenderer.setViewport(0, 0, w, h);
}

// ---------- Animation loop ----------
let prev = performance.now();
function loop(now) {
  const dt = Math.min(0.05, (now - prev) / 1000);
  prev = now;
  updateMainCam(dt);
  for (const m of monitors) m.update();
  mainRenderer.clear();
  mainRenderer.render(scene, mainCam);
  renderAxesOverlay();
  for (const m of monitors) m.render();
  requestAnimationFrame(loop);
}
requestAnimationFrame(loop);
